### ISSUE TITLE
latest revision does not compile with gcc4.4

### ISSUE THREAD

**Issue by PeterSchiffer** [CRPropa/CRPropa3#2]
31.10. use of randBin to simplify several SourceProperties 

I get the following output:

Building CXX object CMakeFiles/crpropa.dir/src/module/Observer.cpp.o  
[ 57%] /afs/desy.de/group/pheno/software/SL6/CRPropa3/src/Random.cpp: In function ‘size_t crpropa::randBin(const std::vector<double, std::allocator<double> >&)’:  
/afs/desy.de/group/pheno/software/SL6/CRPropa3/src/Random.cpp:126: error: ‘lower_bound’ is not a member of ‘std’  
/afs/desy.de/group/pheno/software/SL6/CRPropa3/src/Random.cpp:127: error: ‘rand’ was not declared in this scope  
Building CXX object CMakeFiles/crpropa.dir/src/module/SimplePropagation.cpp.o  
[ 58%] make[2]: **\* [CMakeFiles/crpropa.dir/src/Random.cpp.o] Error 1  
make[2]: **\* Waiting for unfinished jobs....  
Building CXX object CMakeFiles/crpropa.dir/src/module/DeflectionCK.cpp.o  
/afs/desy.de/group/pheno/software/SL6/CRPropa3/src/Source.cpp: In member function ‘virtual void crpropa::SourceDensityGrid::prepare(crpropa::ParticleState&) const’:  
/afs/desy.de/group/pheno/software/SL6/CRPropa3/src/Source.cpp:217: error: no matching function for call to ‘crpropa::Random::randBin(std::vector<float, std::allocator<float> >&)’  
/afs/desy.de/group/pheno/software/SL6/CRPropa3/include/crpropa/Random.h:136: note: candidates are: size_t crpropa::Random::randBin(const std::vector<double, std::allocator<double> >&)  
/afs/desy.de/group/pheno/software/SL6/CRPropa3/src/Source.cpp: In member function ‘virtual void crpropa::SourceDensityGrid1D::prepare(crpropa::ParticleState&) const’:  
/afs/desy.de/group/pheno/software/SL6/CRPropa3/src/Source.cpp:247: error: no matching function for call to ‘crpropa::Random::randBin(std::vector<float, std::allocator<float> >&)’  
/afs/desy.de/group/pheno/software/SL6/CRPropa3/include/crpropa/Random.h:136: note: candidates are: size_t crpropa::Random::randBin(const std::vector<double, std::allocator<double> >&)
