### ISSUE TITLE
Problems installing CRPropa on my system - Centos

### ISSUE THREAD

**Issue by regiopires** [CRPropa/CRPropa3#270]
Dear developers,

I have problems installing CRPropa on my system
**System Information: (Please fill out the following information)**
 - Operating system: 
   Red Hat Enterprise Linux Server release 7.6

 - Laptop or computing cluster?
   Computing cluster

 - Python version: [e.g. 2.7, 3.7, ...]
   Python 2.7.15

 - Swig version: [swig -version]
   SWIG Version 2.0.10
 - Cmake version: [cmake --version]
   cmake version 2.8.12.2

**Did you install CRPropa from git or download a release?**
I installed version 3.1.6 from the releases.

**Things that I tried before asking for help:**
I read and followed the installation instructions at https://github.com/CRPropa/CRPropa3/wiki/Installation . Before writing this request I also checked previous installation issues at https://github.com/CRPropa/CRPropa3/issues? Yes
utf8=%E2%9C%93&q=is%3Aissue+label%3Ainstallation+ . However, this did not work. I receive the following output:

After make:
[ 84%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/ParticleMapsContainer.cpp.o
Linking CXX shared library libcrpropa.so
[ 84%] Built target crpropa
[ 85%] Generating crpropa_wrap.cxx
/prj/prjssisd/sources/crpropa3/3.1.6/CRPropa3-3.1.6/include/crpropa/Vector3.h:39: Warning 312: Nested union not currently supported (ignored).
/prj/prjssisd/sources/crpropa3/3.1.6/CRPropa3-3.1.6/include/crpropa/Vector3.h:41: Error: Syntax error in input(3).
make[2]: ** [crpropa_wrap.cxx] Erro 1
make[1]: ** [CMakeFiles/crpropa-swig.dir/all] Erro 2
make: ** [all] Erro 2

**Comment by adundovi** [comment]
Dear @regiopires,

I'm afraid that you should update SWIG to at least SWIG 3 (~2014). We have recently started to use C++11 features which are supported from SWIG 3 (see [[1]](http://www.swig.org/Doc3.0/CPlusPlus11.html)). Which compiler do you use?

**Comment by rafaelab** [comment]
I confirm this bug. 
I have tested several combinations of GCC versions (6.5, 7.4, 9.3), and SWIG (3.0.12, 4.0.1).

I have been trying to solve this problem for days and still haven't found a solution. When I deactivate python support, CRPropa compiles just fine. Therefore, I suppose the problem is SWIG-related. However,  I don't understand why the same SWIG version works in my laptop but not in the cluster.

I will investigate this further.

**Comment by adundovi** [comment]
@rafaelab Thanks for updating this issue. Make sure that CMake really finds the correct SWIG - that is the first that pops up in my mind. For example, when I compile with SWIG 4.0.1, I have the warning:
```
[ 88%] Generating crpropa_wrap.cxx
.virtualenvs/jupyter/crpropa3_build/include/crpropa/Vector3.h:39: Warning 312: Nested union not currently supported (ignored).
```
but not the next one:
```
/prj/prjssisd/sources/crpropa3/3.1.6/CRPropa3-3.1.6/include/crpropa/Vector3.h:41: Error: Syntax error in input(3).
```
If we inspect which line it is:
```c++
        Vector3() : data{0., 0., 0.} {
```
that's a list initializer [present](https://en.cppreference.com/w/cpp/language/list_initialization) from C++11, and [supported](http://www.swig.org/Doc3.0/CPlusPlus11.html) from SWIG 3.0. Therefore, I don't know why else one would encounter this error if it is not due to older version of SWIG.

**Comment by rafaelab** [comment]
I am pretty sure that all versions I'm using are the right ones because I'm explicitly writing down their path  when running cmake.

The warning message is familiar - I almost always get it. But the error is something new.

I have spent all day digging into this a little further. 
The problem apparently is that SWIG 3+ does not accept nested structures. In Vector3 we have class, union, and struct. 
I tried SWIG's 'flatnested' option in the .i file, with no success.

But I really don't understand why this works in some systems and not in this particular one.

**Comment by rafaelab** [comment]
There was an older version of CRPropa installed by the admin of the cluster where I was trying to do my installation. It was conflicting with the one I was installing (I don't understand how), hence the missing list initializer for Vector3.
@regiopires: Could you make sure that there are no conflicting versions of the code? 
If you install a newer version of SWIG, as @adundovi said, make sure it is the right one being used.

**Comment by adundovi** [comment]
@rafaelab So now you resolved your issue? May I close this ticket?
(Probably cmake found the headers of that other version somehow instead of the one in your build directory)

**Comment by rafaelab** [comment]
This is also the only explanation I could come up with.
I was waiting for @regiopires to reply before closing this issue, but I guess we can close it for now.

**Comment by regiopires** [comment]
Me desculpem a a demora em responder....

Mas respondendo as perguntas: 
Sim, Eu Atualizei. Mas não funciona.

Só funciona quando de desabilito o Suporte a Python
