### ISSUE TITLE
'uint' was not declared

### ISSUE THREAD

**Issue by rafaelab** [CRPropa/CRPropa3#89]
`uint' seems to having been removed from GCC >= 4.7.
I'm getting the error message below when compiling. Solution: replace uint with unsigned int in EMCascade.h.

In file included from /Software/CRPropa3/src/module/EMCascade.cpp:1:0:
/Software/CRPropa3/include/crpropa/module/EMCascade.h:19:22: error: ‘uint’ was not declared in this scope
  mutable std::vector<uint> photonHist;
                      ^
/Software/CRPropa3/include/crpropa/module/EMCascade.h:19:26: error: template argument 1 is invalid
  mutable std::vector<uint> photonHist;

**Comment by geromueller** [comment]
Also, please use uint64_t to prevent overflows.

**Comment by DavidWalz** [comment]
> `uint' seems to having been removed from GCC >= 4.7

mmh, works with with GCC 6.1.1

**Comment by rafaelab** [comment]
I've tested GCC 4.9 and 5.2. Didn't work.
