### ISSUE TITLE
Failed to build with intel/16.0

### ISSUE THREAD

**Issue by DavidWalz** [CRPropa/CRPropa3#64]
On the new CentOS 7 node of the RWTH compute cluster
```
Linking CXX executable crpropa-xmlrun
/opt/intel/Compiler/16.0/2.181/rwthlnk/compiler/lib/intel64_lin/libirng.so: undefined reference to `__intel_mic_avx512f_memcpy'
/opt/intel/Compiler/16.0/2.181/rwthlnk/compiler/lib/intel64_lin/libirng.so: undefined reference to `__intel_avx_rep_memcpy'
```

**Comment by geromueller** [comment]
Try a clean build directory. I had major compile problems at first too. I should compile fine, it does for me now.

**Comment by DavidWalz** [comment]
Ok solved, I had only deleted CMakeCache.txt
Thanks!
